//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsole.MsmqServiceBridge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MsmqServiceBridge.IMsmqContract")]
    public interface IMsmqContract {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMsmqContract/ProcessMessage")]
        void ProcessMessage(int value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMsmqContract/ProcessMessage")]
        System.Threading.Tasks.Task ProcessMessageAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMsmqContractChannel : ClientConsole.MsmqServiceBridge.IMsmqContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsmqContractClient : System.ServiceModel.ClientBase<ClientConsole.MsmqServiceBridge.IMsmqContract>, ClientConsole.MsmqServiceBridge.IMsmqContract {
        
        public MsmqContractClient() {
        }
        
        public MsmqContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MsmqContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsmqContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsmqContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ProcessMessage(int value) {
            base.Channel.ProcessMessage(value);
        }
        
        public System.Threading.Tasks.Task ProcessMessageAsync(int value) {
            return base.Channel.ProcessMessageAsync(value);
        }
    }
}
